name: Install

on:
  workflow_dispatch:
  push:
    branches:
      - '*'

jobs:
  Apple:
    runs-on: macos-latest
    steps:
      - name: Install
        run: brew install --ignore-dependencies libxcb
      - name: Upload usr
        uses: actions/upload-artifact@v2
        with:
          name: usr
          path: /usr/local/Cellar/libxcb/**/*
          
