name: Install

on:
  workflow_dispatch:
  push:
    branches:
      - '*'

jobs:
  Apple:
    runs-on: macos-latest
    steps:
      - name: Install
        run: brew install ffmpeg
      - name: Upload usr
        uses: actions/upload-artifact@v2
        with:
          name: usr1
          path: /usr/local/Cellar/libxau/**/*
      - name: Upload FFmpeg Dependencies
        uses: actions/upload-artifact@v2
        with:
          name: ffmpeg-dependencies-macos
          path: |
            /usr/local/Cellar/aom/**/*
            /usr/local/Cellar/aribb24/**/*
            /usr/local/Cellar/dav1d/**/*
            /usr/local/Cellar/fontconfig/**/*
            /usr/local/Cellar/freetype/**/*
            /usr/local/Cellar/frei0r/**/*
            /usr/local/Cellar/gnutls/**/*
            /usr/local/Cellar/jpeg-xl/**/*
            /usr/local/Cellar/lame/**/*
            /usr/local/Cellar/libass/**/*
            /usr/local/Cellar/libbluray/**/*
            /usr/local/Cellar/librist/**/*
            /usr/local/Cellar/libsoxr/**/*
            /usr/local/Cellar/libvidstab/**/*
            /usr/local/Cellar/libvmaf/**/*
            /usr/local/Cellar/libvorbis/**/*
            /usr/local/Cellar/libvpx/**/*
            /usr/local/Cellar/opencore-amr/**/*
            /usr/local/Cellar/openjpeg/**/*
            /usr/local/Cellar/opus/**/*
            /usr/local/Cellar/rav1e/**/*
            /usr/local/Cellar/rubberband/**/*
            /usr/local/Cellar/sdl2/**/*
            /usr/local/Cellar/snappy/**/*
            /usr/local/Cellar/speex/**/*
            /usr/local/Cellar/srt/**/*
            /usr/local/Cellar/svt-av1/**/*
            /usr/local/Cellar/tesseract/**/*
            /usr/local/Cellar/theora/**/*
            /usr/local/Cellar/webp/**/*
            /usr/local/Cellar/x264/**/*
            /usr/local/Cellar/x265/**/*
            /usr/local/Cellar/xvid/**/*
            /usr/local/Cellar/xz/**/*
            /usr/local/Cellar/zeromq/**/*
            /usr/local/Cellar/libpng/**/*
            /usr/local/Cellar/ca-certificates/**/*
            /usr/local/Cellar/gmp/**/*
            /usr/local/Cellar/libidn2/**/*
            /usr/local/Cellar/libtasn1/**/*
            /usr/local/Cellar/libunistring/**/*
            /usr/local/Cellar/nettle/**/*
            /usr/local/Cellar/p11-kit/**/*
            /usr/local/Cellar/unbound/**/*
            /usr/local/Cellar/gettext/**/*
            /usr/local/Cellar/libevent/**/*
            /usr/local/Cellar/libnghttp2/**/*
            /usr/local/Cellar/openssl/**/*
            /usr/local/Cellar/brotli/**/*
            /usr/local/Cellar/giflib/**/*
            /usr/local/Cellar/highway/**/*
            /usr/local/Cellar/imath/**/*
            /usr/local/Cellar/jpeg-turbo/**/*
            /usr/local/Cellar/little-cms2/**/*
            /usr/local/Cellar/openexr/**/*
            /usr/local/Cellar/webp/**/*
            /usr/local/Cellar/libtiff/**/*
            /usr/local/Cellar/zstd/**/*
            /usr/local/Cellar/fribidi/**/*
            /usr/local/Cellar/harfbuzz/**/*
            /usr/local/Cellar/cairo/**/*
            /usr/local/Cellar/glib/**/*
            /usr/local/Cellar/graphite2/**/*
            /usr/local/Cellar/icu4c/**/*
            /usr/local/Cellar/libx11/**/*
            /usr/local/Cellar/libxcb/**/*
            /usr/local/Cellar/libxext/**/*
            /usr/local/Cellar/libxrender/**/*
            /usr/local/Cellar/lzo/**/*
            /usr/local/Cellar/pixman/**/*
            /usr/local/Cellar/pcre2/**/*
            /usr/local/Cellar/xorgproto/**/*
            /usr/local/Cellar/libxau/**/*
            /usr/local/Cellar/libxdmcp/**/*
            /usr/local/Cellar/cjson/**/*
            /usr/local/Cellar/mbedtls/**/*
            /usr/local/Cellar/libogg/**/*
            /usr/local/Cellar/libsamplerate/**/*
            /usr/local/Cellar/libsndfile/**/*
            /usr/local/Cellar/flac/**/*
            /usr/local/Cellar/mpg123/**/*
            /usr/local/Cellar/leptonica/**/*
            /usr/local/Cellar/libarchive/**/*
            /usr/local/Cellar/pango/**/*
            /usr/local/Cellar/libb2/**/*
            /usr/local/Cellar/lz4/**/*
            /usr/local/Cellar/libsodium/**/*
            /usr/local/Cellar/zimg/**/*
          
