name: Install

on:
  workflow_dispatch:
  push:
    branches:
      - '*'

jobs:
  Apple:
    runs-on: macos-latest
    steps:
      - name: Install
        run: brew install --ignore-dependencies libxau libxdmcp
      - name: Upload usr
        uses: actions/upload-artifact@v2
        with:
          name: usr1
          path: /usr/local/Cellar/libxau/**/*
      - name: Upload usr
        uses: actions/upload-artifact@v2
        with:
          name: usr2
          path: /usr/local/Cellar/libxdmcp/**/*
          
