name: Install

on:
  workflow_dispatch:
  push:
    branches:
      - '*'

jobs:
  Apple:
    runs-on: macos-latest
    steps:
      #- name: Install
      #  run: brew install ffmpeg
      - name: Upload FFmpeg Dependencies
        uses: actions/upload-artifact@v2
        with:
          name: ffmpeg-dependencies-macos
          path: |
            /usr/lib/libSystem.B.dylib
            /usr/lib/libiconv.2.dylib
            /usr/lib/libz.1.dylib
            /usr/lib/libc++.1.dylib
          
