name: Install

on:
  workflow_dispatch:

jobs:
  Apple:
    runs-on: macos-latest
    steps:
      - name: Setup tap
        run: brew tap homebrew-ffmpeg/ffmpeg
      - name: Install
        run: brew install homebrew-ffmpeg/ffmpeg/ffmpeg
      - name: Upload usr
        uses: actions/upload-artifact@v2
        with:
          name: usr
          path: /usr/local/Cellar/ffmpeg/**/*
          
